# 🌐 ORO EXAM SYSTEM INTERNATIONALIZATION (I18N) MODULE
# Provides standard localized strings for multi-lingual exam distribution.

LANGUAGES = {
    "en": {
        "title": "Oro Exam System",
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "role": "Role",
        "login_success": "Login Successful! Loading dashboard...",
        "login_fail": "Invalid username or password ❌",
        "login_locked": "Account Locked! Too many failed attempts. 🔒",
        "student_dashboard": "Student Dashboard",
        "teacher_dashboard": "Teacher Dashboard",
        "admin_dashboard": "Admin Dashboard",
        "start_exam": "Start MCQ Exam",
        "leaderboard": "Leaderboard Ranking",
        "logout": "Logout",
        "question": "Question",
        "prev": "Previous",
        "next": "Next",
        "finish": "Finish Exam 🏁",
        "add_question": "Add Question",
        "reset_db": "Reset Results Database Table",
        "db_stats": "Database Statistics",
        "total_attempts": "Total Logged Attempts",
        "avg_score": "Average Score",
        "certificate_title": "ORO EXAM RESULT",
        "certificate_generated": "Automated report generated by Oro System."
    },
    "es": {
        "title": "Sistema de Examen Oro",
        "login": "Iniciar Sesión",
        "username": "Usuario",
        "password": "Contraseña",
        "role": "Rol",
        "login_success": "¡Inicio de sesión exitoso! Cargando panel...",
        "login_fail": "Usuario o contraseña inválidos ❌",
        "login_locked": "¡Cuenta Bloqueada! Demasiados intentos fallidos. 🔒",
        "student_dashboard": "Panel de Estudiante",
        "teacher_dashboard": "Panel de Profesor",
        "admin_dashboard": "Panel de Administrador",
        "start_exam": "Comenzar Examen de Opción Múltiple",
        "leaderboard": "Clasificación de Líderes",
        "logout": "Cerrar Sesión",
        "question": "Pregunta",
        "prev": "Anterior",
        "next": "Siguiente",
        "finish": "Terminar Examen 🏁",
        "add_question": "Añadir Pregunta",
        "reset_db": "Restablecer Tabla de Resultados",
        "db_stats": "Estadísticas de Base de Datos",
        "total_attempts": "Total de Intentos Registrados",
        "avg_score": "Puntuación Promedio",
        "certificate_title": "RESULTADO DEL EXAMEN ORO",
        "certificate_generated": "Informe automatizado generado por el Sistema Oro."
    },
    "fr": {
        "title": "Système d'Examen Oro",
        "login": "Connexion",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "role": "Rôle",
        "login_success": "Connexion réussie! Chargement du tableau...",
        "login_fail": "Nom d'utilisateur ou mot de passe invalide ❌",
        "login_locked": "Compte verrouillé! Trop de tentatives infructueuses. 🔒",
        "student_dashboard": "Tableau de bord de l'étudiant",
        "teacher_dashboard": "Tableau de bord de l'enseignant",
        "admin_dashboard": "Tableau de bord de l'administrateur",
        "start_exam": "Commencer l'examen QCM",
        "leaderboard": "Classement des leaders",
        "logout": "Se déconnecter",
        "question": "Question",
        "prev": "Précédent",
        "next": "Suivant",
        "finish": "Terminer l'examen 🏁",
        "add_question": "Ajouter une question",
        "reset_db": "Réinitialiser la base de données",
        "db_stats": "Statistiques de la base de données",
        "total_attempts": "Nombre total de tentatives",
        "avg_score": "Score moyen",
        "certificate_title": "RÉSULTAT DE L'EXAMEN ORO",
        "certificate_generated": "Rapport automatisé généré par le système Oro."
    }
}

CURRENT_LANG = "en"

def set_language(lang_code):
    """Sets the system-wide active language."""
    global CURRENT_LANG
    if lang_code in LANGUAGES:
        CURRENT_LANG = lang_code

def t(key):
    """Translates a key into the currently active language."""
    return LANGUAGES.get(CURRENT_LANG, LANGUAGES["en"]).get(key, key)
