from reportlab.pdfgen import canvas

def generate_result_pdf(student, score, total):
    file = f"{student}_result.pdf"
    c = canvas.Canvas(file)
    
    # Header Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(180, 780, "ORO EXAM RESULT")
    
    # Decorative Horizontal Line
    c.setLineWidth(1)
    c.line(100, 760, 500, 760)
    
    # Result Details Section
    c.setFont("Helvetica", 14)
    c.drawString(100, 700, "Student Name:")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(250, 700, f"{student}")
    
    c.setFont("Helvetica", 14)
    c.drawString(100, 660, "Correct Answers:")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(250, 660, f"{score} / {total}")
    
    percent = int((score / total) * 100) if total > 0 else 0
    c.setFont("Helvetica", 14)
    c.drawString(100, 620, "Percentage Score:")
    c.setFont("Helvetica-Bold", 14)
    c.drawString(250, 620, f"{percent}%")
    
    status = "PASS" if score >= total / 2 else "FAIL"
    c.setFont("Helvetica", 14)
    c.drawString(100, 580, "Passing Status:")
    if status == "PASS":
        c.setFillColorRGB(0.1, 0.6, 0.2) # Green for pass
    else:
        c.setFillColorRGB(0.8, 0.2, 0.2) # Red for fail
    c.setFont("Helvetica-Bold", 16)
    c.drawString(250, 580, f"{status}")
    
    # Reset color
    c.setFillColorRGB(0, 0, 0)
    
    # Footer Section
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(100, 150, "This is an automated performance report generated by the Oro Exam System.")
    c.drawString(100, 135, "Congratulations on completing your exam!")
    
    c.save()
    return file
